Create sql table.md
bellshade/SQL pull request #22
Opened 2021-11-08 15:15 UTC by Aliya1227

2021-11-08 16:34 UTC, KelvinMulyawan commented
@Aliya1227 Gnight, sorry for late review okay, thank you for PR in Bellshade SQL Repository
Gini, pertama, kamu harus teliti dulu ya sama Typo, itu aja
Kedua, materi nya udah di limit based on silabus, jadi cukup singkat aja
Misalnya bikin tabel, cukup dari create dan selesai di drop
kalau mau alter, bisa di bikin nanti sendiri, kami dari reviewer bakalan coba koneksi kan setiap materi yang ada, jadi tenang aja
Overall, 91/100, Semangat @Aliya1227 thank u

2021-11-08 16:45 UTC, mhaikalla commented
halo @Aliya1227  itu kan kamu bikin PR tentang create table yaa, itu sebenarnya udah disediain file file nya jadi tinggal pakai file yang udah ada, nanti materi materi nya tingall ditaruh disitu deh heheh

Nanti next nya kalau mau masukin materi baru, masukin di file yang udah ada yaa, kalau belum ada bisa ditambah aja file baru 

gpp nanti ku merge materinya 

Thank you

2021-11-09 04:09 UTC, Aliya1227 commented
oh ok kak , sebelumnya saya udah pernah buat pr beberapa kali di HTML-CSS jadi saya kira aturannya sama, kalau gitu saya perbaiki dulu

2021-11-09 04:10 UTC, Aliya1227 commented
limit katanya berapa kak ?

2021-11-09 05:04 UTC, mhaikalla commented
@Aliya1227 iya gpp, sebenarnya sih disini udah dibikin mappingan file nya supaya lebih rapi nyusun nya jadi ga berantakan dan file file disini masih banyak yang kosong sih karna belum banyak materi yang masuk, nanti yang udah terlanjur kamu kerjakan nanti saya merge aja dengan materi lain biar penyusunan repo nya lebih rapih, bisa dilihat di issue ada list file dan folder yang belum diisi materi

2021-11-09 05:06 UTC, mhaikalla commented
@Aliya1227  Limit nya bebas jangan terlalu kedikitan juga dan yang penting penjelasanya clear sih dan gampang dipahami

2021-11-09 05:08 UTC, mhaikalla commented
@Aliya1227 ohiya setiap commit dikasih message yaa ada aturan nya soalnya nanti detailnya saya tulis di issue, yang jelas kalau mau commit bisa nulis

kalau fix penulisan tulis
fix:message

kalau mau nambah materi baru:
add:message

2021-11-09 06:32 UTC, mhaikalla reviewed
Ini ane merge aja karna ddl udah ane bikin semua

2021-11-10 09:14 UTC, Aliya1227 commented
maaf kak saya baru buka bellshade lagi, itu maksudnya saya hapus saja PR yang ini , dan isi file disini saya bagi 2 ke dua file berbeda , file create table.md & alter table.md buat do PR kembali ke folder pengenalan ?

2021-11-10 13:30 UTC, agnes-diza-fahira requested changes
Halo @Aliya1227 , makasih ya sudah ngePR di SQL, berikut aku kasih saran di suggestion biar keliatan lebih rapih ya. Sama tambahan untuk menghapus setauku ada tambahan fungsi `TRUNCATE` untuk menghapus data pada tabel tanpa menghapus tabelnya (jadi tabelnya kosong), mungkin bisa dicek lagi. Sekian review dari ku, semangatt!! @Aliya1227

2021-11-10 13:30 UTC, agnes-diza-fahira commented on SQL TABLE/sql table.md
> +1.Ketika membuat nama tabel atau nama kolom dan terdiri dari 2 kata atau lebih gunakan tanda ``_`` sebagai pengganti spasi.
Bisa dienter sekali lagi biar 1 ke 2nya keenter di preview dan terlihat lebih rapih. Begitu juga 2 ke 3

2021-11-10 13:30 UTC, agnes-diza-fahira commented on SQL TABLE/sql table.md
> +### MenghapuS kolom dari tabel
```suggestion
### Menghapus kolom dari tabel
```

2021-11-11 02:41 UTC, mhaikalla commented
> 
> 
> maaf kak saya baru buka bellshade lagi, itu maksudnya saya hapus saja PR yang ini , dan isi file disini saya bagi 2 ke dua file berbeda , file create table.md & alter table.md buat di PR kembali ke folder pengenalan ?

sbb yang udah terlanjur PR gpp nanti ane merge lagi, santuy wkwk, mending lanjutin materi yang lain yang belum diisi tuh

2021-11-15 14:41 UTC, Aliya1227 commented
jadi kalau mau PR lagi langsung saja porpose changes ?

2021-11-16 13:42 UTC, mhaikalla commented
tidak perlu, pr ini aku merge yaa

2021-11-16 13:42 UTC, merged