feat: menambahkan meteri limit
bellshade/SQL pull request #56
Opened 2022-01-22 03:25 UTC by fairusatoir

Issue #30 

- [x] 6.LIMIT

2022-01-25 09:12 UTC, AdityaFitrianaNS requested changes
```suggestion
**LIMIT** digunakan pada tabel yang memiliki ribuan atau lebih data karena saat memberikan data yang berjumlah besar, kinerja dari database akan ikut terpengaruhi.
```

2022-01-25 16:17 UTC, fairusatoir commented
> Beberapa ada yang kurang tanda titik setiap akhir kata. pada line : 9, 16, 26, 36, 48

done

2022-01-26 11:24 UTC, AdityaFitrianaNS approved these changes
LGTM kak!

2022-01-27 15:36 UTC, mhaikalla approved these changes
Approved

2022-01-27 15:37 UTC, merged