feat: query schema dasar
bellshade/SQL pull request #8
Opened 2021-10-14 13:02 UTC by fairusatoir

issue #5

2021-10-16 07:50 UTC, Vins2106 approved these changes
lgtm

2021-10-17 15:18 UTC, fairusatoir commented
tambahan issue #7

2021-10-19 02:46 UTC, nomadkode requested changes
diperbaiki lagi yaa om typo nya.

2021-10-19 02:46 UTC, nomadkode commented on SQL Group By/GROUP_BY.md
> +COntoh - kita ingin mengelompokan data berdasar kolom `Nama`
```suggestion
contoh - kita ingin mengelompokkan data berdasar kolom `Nama`
```

2021-10-19 02:46 UTC, nomadkode commented on SQL Group By/GROUP_BY.md
> +contoh - Jumlahkan total barang yang dibeli berasarkan `Nama`
```suggestion
contoh - Jumlahkan total barang yang dibeli berdasarkan `Nama`
```

2021-10-19 02:46 UTC, nomadkode commented on SQL Group By/GROUP_BY.md
> +contoh - rata-rata barang yang dibeli berasarkan `Nama`
```suggestion
contoh - rata-rata barang yang dibeli berdasarkan `Nama`
```

2021-10-19 02:46 UTC, nomadkode commented on SQL Group By/GROUP_BY.md
> +contoh - minimal dan maksimal barang yang dibeli berasarkan `Nama`
```suggestion
contoh - minimal dan maksimal barang yang dibeli berdasarkan `Nama`
```

2021-10-19 02:46 UTC, nomadkode commented on SQL Group By/GROUP_BY.md
> +## Menggunkan 2 Kolom
```suggestion
## Menggunakan 2 Kolom
```

2021-10-19 02:46 UTC, nomadkode commented on SQL Group By/GROUP_BY.md
> +Jika ingin 2 kolom yang ingin ditampilkan, maka `GROUP BY` tambahkan kolom yang ingin ditampilkan tetapi itu akan
akan apa?

2021-10-19 02:46 UTC, nomadkode commented on SQL Group By/GROUP_BY.md
> +### Sintak
```suggestion
### Sintaks
```

2021-10-19 02:46 UTC, nomadkode commented on SQL Group By/GROUP_BY.md
> +## Menggunkan COUNT, MAX, MIN, SUM dan AVG
```suggestion
## Menggunakan COUNT, MAX, MIN, SUM dan AVG
```

2021-10-19 02:46 UTC, nomadkode commented on SQL Group By/GROUP_BY.md
> +## Menggunkan 2 Tabel
```suggestion
## Menggunakan 2 Tabel
```

2021-10-19 02:46 UTC, nomadkode commented on SQL Schema/SQL_Schema_Dasar.md
> +Didalam sebuah **SQL Database** terdapat banyak **Schema** (**Skema**) yang bertujuan untuk memisahkan perngguan aplikasi yang berbeda dan pembagian hak akses.
```suggestion
Di dalam sebuah **SQL Database** terdapat banyak **Schema** (**Skema**) yang bertujuan untuk memisahkan perngguan aplikasi yang berbeda dan pembagian hak akses.
```
```suggestion
Didalam sebuah **SQL Database** terdapat banyak **Schema** (**Skema**) yang bertujuan untuk memisahkan perngguan aplikasi yang berbeda dan pembagian hak akses.
```

2021-10-19 03:08 UTC, fairusatoir commented
perbaikan telah selesai dilakukan

2021-10-19 08:09 UTC, nomadkode commented on SQL Group By/GROUP_BY.md
> +## MenggunakanCOUNT, MAX, MIN, SUM dan AVG
```suggestion
## Menggunakan COUNT, MAX, MIN, SUM dan AVG
```

2021-10-19 08:10 UTC, nomadkode approved these changes
LGTM 🚀

2021-10-19 08:11 UTC, merged

2021-10-19 08:13 UTC, fairusatoir commented on SQL Group By/GROUP_BY.md
> +## MenggunakanCOUNT, MAX, MIN, SUM dan AVG
thx mas, maaf kelewatan